<?php

/**
 * @file
 */

/**
 * @see RestWSTestCase::testMenuPath().
 */
function restws_test_restws_resource_info_alter(&$resource_info) {
  $menu_path = variable_get('restws_test_menu_path', 'foo');
  $resource_info['node']['menu_path'] = $menu_path;
}

/**
 * @see RestWSTestCase::testFieldAccess()
 */
function restws_test_field_access($op, $field, $entity_type, $entity, $account) {
  if ($field['field_name'] == 'field_text' && $op == 'edit') {
    return user_access('administer users', $account);
  }
  return TRUE;
}
