<?php

/**
 * @file
 */

/**
 * Implements hook_help().
 */
function jquery_update_help($path, $arg) {
  switch ($path) {
    case 'admin/config/development/jquery_update':
      return '<p>' . t('Configure how <a href="@jquery">jQuery</a> behaves on the site. Select which jQuery version, the compression level and whether or not to use a CDN.', array(
        '@jquery' => 'http://jquery.com',
      )) . '</p>';
  }
}

/**
 * Implements hook_library().
 */
function jquery_update_library() {
  $path = drupal_get_path('module', 'jquery_update') . '/ui/external';
  $libraries['qunit'] = array(
    'title' => 'QUnit',
    'js' => array(
      $path . '/qunit.js' => array(
        'group' => JS_LIBRARY,
        'weight' => 2,
      ),
    ),
    'css' => array(
      $path . '/qunit.css' => array(),
    ),
    'version' => '1.11.0',
  );
  $libraries['jquery_update.ajax.fix'] = array(
    'title' => 'jQuery Update Version Fix',
    'js' => array(
      drupal_get_path('module', 'jquery_update') . '/js/jquery_update.js' => array(
        'group' => JS_LIBRARY,
        'weight' => 3,
      ),
    ),
    'version' => '0.0.1',
  );
  $libraries['jquery.metadata'] = array(
    'title' => 'QUnit',
    'js' => array(
      $path . '/jquery.metadata.js' => array(
        'group' => JS_LIBRARY,
        'weight' => 2,
      ),
    ),
    'version' => '4187',
  );
  $libraries['jquery.bgiframe'] = array(
    'title' => 'bgiframe',
    'website' => 'http://docs.jquery.com/Plugins/bgiframe',
    'js' => array(
      $path . '/jquery.bgiframe.js' => array(
        'group' => JS_LIBRARY,
        'weight' => 2,
      ),
    ),
    'version' => '2.1.2',
  );
  return $libraries;
}

/**
 * Implements hook_library_alter().
 */
function jquery_update_library_alter(&$javascript, $module) {
  $path = drupal_get_path('module', 'jquery_update');
  $version = variable_get('jquery_update_jquery_version', '1.10');


  if ($module === 'system') {

    $min = variable_get('jquery_update_compression_type', 'min') == 'none' ? '' : '.min';
    $cdn = variable_get('jquery_update_jquery_cdn', 'none');

    $admin_version = variable_get('jquery_update_jquery_admin_version', '');

    if (!empty($admin_version) && path_is_admin(current_path())) {
      if (version_compare($version, $admin_version, '!=')) {
        $version = $admin_version;
      }
    }
    if (!empty($_POST['ajax_page_state']['jquery_version'])) {
      $ajax_version = $_POST['ajax_page_state']['jquery_version'];
      if (in_array($ajax_version, array('default', '1.5', '1.6', '1.7', '1.8', '1.9', '1.10'))) {
        $version = $ajax_version;
      }
    }

    $javascript['drupal.ajax']['js'][] = array(
      'data' => array('ajaxPageState' => array('jquery_version' => $version)),
      'type' => 'setting',
    );
    $javascript['drupal.ajax']['dependencies'][] = array('jquery_update', 'jquery_update.ajax.fix');

    if ('default' == $version) {
      return;
    }

    jquery_update_jquery_replace($javascript, $cdn, $path, $min, $version);

    if (version_compare($version, '1.6', '>=')) {
      jquery_update_jqueryui_replace($javascript, $cdn, $path, $min);
    }

    $javascript['cookie']['js']['misc/jquery.cookie.js']['data'] = $path . '/replace/ui/external/jquery.cookie.js';
    $javascript['cookie']['version'] = '67fb34f6a866c40d0570';

    $javascript['jquery.form']['js']['misc/jquery.form.js']['data'] = $path . '/replace/misc/jquery.form' . $min . '.js';
    $javascript['jquery.form']['version'] = '2.69';

    if (version_compare($version, '1.9', '>=')) {
      $javascript['jquery.bbq']['js']['misc/jquery.ba-bbq.js']['data'] = $path . '/replace/misc/1.9/jquery.ba-bbq' . $min . '.js';
    }
  }

  if ($module == 'overlay') {
    if (version_compare($version, '1.9', '>=')) {
      $javascript['parent']['js']['modules/overlay/overlay-parent.js']['data'] = $path . '/replace/misc/1.9/overlay-parent.js';
    }
  }
}

/**
 * Implements hook_menu().
 */
function jquery_update_menu() {
  $items['admin/config/development/jquery_update'] = array(
    'title' => 'jQuery update',
    'description' => 'Configure settings related to the jQuery upgrade, the library path and compression.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('jquery_update_settings_form'),
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * @see jquery_update_menu()
 */
function jquery_update_settings_form() {
  $form['version_options'] = array(
    '#type' => 'fieldset',
    '#title' => t('Version options'),
  );

  $form['version_options']['jquery_update_jquery_version'] = array(
    '#type' => 'select',
    '#title' => t('Default jQuery Version'),
    '#options' => array(
      'default' => t('Default (provided by Drupal)'),
      '1.5' => '1.5',
      '1.7' => '1.7',
      '1.8' => '1.8',
      '1.9' => '1.9',
      '1.10' => '1.10',
    ),
    '#default_value' => variable_get('jquery_update_jquery_version', '1.10'),
    '#description' => t('Select which jQuery version to use by default.'),
  );

  $form['version_options']['jquery_update_jquery_admin_version'] = array(
    '#type' => 'select',
    '#title' => t('Alternate jQuery version for administrative pages'),
    '#options' => array(
      '' => t('Default jQuery Version'),
      'default' => t('Default (provided by Drupal)'),
      '1.5' => '1.5',
      '1.7' => '1.7',
      '1.8' => '1.8',
      '1.10' => '1.10',
    ),
    '#default_value' => variable_get('jquery_update_jquery_admin_version', ''),
    '#description' => t('Optionally select a different version of jQuery to use on administrative pages.'),
  );

  $form['jquery_update_compression_type'] = array(
    '#type' => 'radios',
    '#title' => t('jQuery compression level'),
    '#options' => array(
      'min' => t('Production (minified)'),
      'none' => t('Development (uncompressed)'),
    ),
    '#states' => array(
      'invisible' => array(
        ':input[name=jquery_update_jquery_version]' => array('value' => "default"),
      ),
    ),
    '#default_value' => variable_get('jquery_update_compression_type', 'min'),
  );
  $form['jquery_update_jquery_cdn'] = array(
    '#type' => 'select',
    '#title' => t('jQuery and jQuery UI CDN'),
    '#options' => array(
      'none' => t('None'),
      'google' => t('Google'),
      'microsoft' => t('Microsoft'),
      'jquery' => t('jQuery'),
    ),
    '#states' => array(
      'invisible' => array(
        ':input[name=jquery_update_jquery_version]' => array('value' => "default"),
      ),
    ),
    '#default_value' => variable_get('jquery_update_jquery_cdn', 'none'),
    '#description' => t('Use jQuery and jQuery UI from a CDN. If the CDN is not available the local version of jQuery and jQuery UI will be used.'),
  );

  return system_settings_form($form);
}

/**
 * @param array $javascript
 * @param string $cdn
 * @param string $path
 * @param string $min
 * @param string $version
 */
function jquery_update_jquery_replace(&$javascript, $cdn, $path, $min, $version) {

  $trueversion = NULL;
  switch ($version) {
    case '1.5':
      $trueversion = '1.5.2';
      break;

    case '1.7':
      $trueversion = '1.7.2';
      break;

    case '1.8':
      $trueversion = '1.8.3';
      break;

    case '1.9':
      $trueversion = '1.9.1';
      break;

    case '1.10':
      $trueversion = '1.10.2';
      break;
  }
  $javascript['jquery']['version'] = $trueversion;

  switch ($cdn) {
    case 'google':
      $javascript['jquery']['js']['misc/jquery.js']['data'] = '//ajax.googleapis.com/ajax/libs/jquery/' . $trueversion . '/jquery' . $min . '.js';
      $javascript['jquery']['js']['misc/jquery.js']['type'] = 'external';
      jquery_update_jquery_backup($javascript, $path, $min, $version);
      break;

    case 'microsoft':
      $javascript['jquery']['js']['misc/jquery.js']['data'] = '//ajax.aspnetcdn.com/ajax/jQuery/jquery-' . $trueversion . $min . '.js';
      $javascript['jquery']['js']['misc/jquery.js']['type'] = 'external';
      jquery_update_jquery_backup($javascript, $path, $min, $version);
      break;

    case 'jquery':
      $javascript['jquery']['js']['misc/jquery.js']['data'] = '//code.jquery.com/jquery-' . $trueversion . $min . '.js';
      $javascript['jquery']['js']['misc/jquery.js']['type'] = 'external';
      jquery_update_jquery_backup($javascript, $path, $min, $version);
      break;

    case 'none':
    default:
      $javascript['jquery']['js']['misc/jquery.js']['data'] = $path . '/replace/jquery/' . $version . '/jquery' . $min . '.js';
      break;
  }
}

/**
 * @param array $javascript
 * @param string $path
 * @param string $min
 * @param string $version
 */
function jquery_update_jquery_backup(&$javascript, $path, $min, $version) {
  $javascript['jquery']['js'][] = array(
    'data' => 'window.jQuery || document.write("<script src=\'' . base_path() . $path . '/replace/jquery/' . $version . '/jquery' . $min . '.js\'>\x3C/script>")',
    'type' => 'inline',
    'group' => JS_LIBRARY,
    'weight' => -19.999999999,
  );
}

/**
 * @param array $javascript
 * @param string $cdn
 * @param string $path
 * @param string $min
 */
function jquery_update_jqueryui_replace(&$javascript, $cdn, $path, $min) {
  $javascript['ui.menu'] = array(
    'title' => 'jQuery UI: Menu',
    'website' => 'http://jqueryui.com/demos/menu/',
    'version' => '1.10.2',
    'js' => array('misc/ui/jquery.ui.menu.min.js' => array()),
    'css' => array('misc/ui/jquery.ui.menu.css' => array()),
    'dependencies' => array(array('system', 'ui.widget'), array('system', 'ui.position')),
  );
  $javascript['ui.spinner'] = array(
    'title' => 'jQuery UI: Spinner',
    'website' => 'http://jqueryui.com/demos/spinner/',
    'version' => '1.10.2',
    'js' => array('misc/ui/jquery.ui.spinner.min.js' => array()),
    'css' => array('misc/ui/jquery.ui.spinner.css' => array()),
    'dependencies' => array(array('system', 'ui.widget'), array('system', 'ui.button')),
  );
  $javascript['ui.tooltip'] = array(
    'title' => 'jQuery UI: Spinner',
    'website' => 'http://jqueryui.com/demos/tooltip/',
    'version' => '1.10.2',
    'js' => array('misc/ui/jquery.ui.tooltip.min.js' => array()),
    'css' => array('misc/ui/jquery.ui.tooltip.css' => array()),
    'dependencies' => array(array('system', 'ui.widget'), array('system', 'ui.position')),
  );

  $javascript['ui.autocomplete']['dependencies'][] = array('system', 'ui.menu');
  $names = drupal_map_assoc(array(
    'ui.accordion', 'ui.autocomplete', 'ui.button', 'ui.datepicker', 'ui.dialog',
    'ui.progressbar', 'ui.resizable', 'ui.selectable', 'ui.slider', 'ui.tabs',
    'ui.menu', 'ui.spinner', 'ui.tooltip',
  ));
  $names['ui'] = 'ui.core';
  $csspath = $path . '/replace/ui/themes/base/' . (($min == '.min') ? 'minified/' : '');
  foreach ($names as $name => $file) {
    $javascript[$name]['css']["misc/ui/jquery.$file.css"]['data'] = $csspath . 'jquery.' . $file . $min . '.css';
  }
  $javascript['ui']['css']['misc/ui/jquery.ui.theme.css']['data'] = $csspath . 'jquery.ui.theme' . $min . '.css';

  $names = drupal_map_assoc(array(
    'ui.accordion', 'ui.autocomplete', 'ui.button', 'ui.datepicker', 'ui.dialog', 'ui.draggable',
    'ui.droppable', 'ui.mouse', 'ui.position', 'ui.progressbar', 'ui.resizable', 'ui.selectable',
    'ui.slider', 'ui.sortable', 'ui.tabs', 'ui.widget', 'ui.spinner', 'ui.menu', 'ui.tooltip',
  ));
  $names['ui'] = 'ui.core';
  $names['effects'] = array('effects.core', 'ui.effect'); 
  $names = jquery_update_make_library_hook_to_file_name_segment_map_for_effects($names);

  switch ($cdn) {
    case 'google':
      $cdn = '//ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui' . $min . '.js';
      jquery_update_jqueryui_cdn($cdn, $javascript, $path, $min, $names);
      jquery_update_jqueryui_backup($javascript, $path, $min);
      break;

    case 'microsoft':
      $cdn = '//ajax.aspnetcdn.com/ajax/jquery.ui/1.10.2/jquery-ui' . $min . '.js';
      jquery_update_jqueryui_cdn($cdn, $javascript, $path, $min, $names);
      jquery_update_jqueryui_backup($javascript, $path, $min);
      break;

    case 'jquery':
      $cdn = '//code.jquery.com/ui/1.10.2/jquery-ui' . $min . '.js';
      jquery_update_jqueryui_cdn($cdn, $javascript, $path, $min, $names);
      jquery_update_jqueryui_backup($javascript, $path, $min);
      break;

    case 'none':
      jquery_update_jqueryui_local($javascript, $path, $min, $names);
      break;
  }
}

/**
 * @param array $map Optional. If given, append to it.
 * @return array The keys are library hooks  and the values are each arrays of
 */
function jquery_update_make_library_hook_to_file_name_segment_map_for_effects($map = array()) {
  $effect_names = array(
    'blind', 'bounce', 'clip', 'drop', 'explode', 'fade', 'fold',
    'highlight', 'pulsate', 'scale', 'shake', 'slide', 'transfer',
  );
  foreach ($effect_names as $effect_name) {
    $library_hook = 'effects.' . $effect_name;
    $file_name_segment_core = $library_hook; // Yes, for the effect files, this is indeed identical.
    $file_name_segment_updated = 'ui.effect-' . $effect_name;
    $map[$library_hook] = array($file_name_segment_core, $file_name_segment_updated);
  }
  return $map;
}

/**
 * @param array $javascript
 * @param string $path
 * @param string $min
 */
function jquery_update_jqueryui_backup(&$javascript, $path, $min) {
  $js_path = ($min == '.min') ? '/replace/ui/ui/minified/jquery-ui.min.js' : '/replace/ui/ui/jquery-ui.js';
  $javascript['ui']['js'][] = array(
    'data' => 'window.jQuery.ui || document.write("<script src=\'' . base_path() . $path . $js_path . '\'>\x3C/script>")',
    'type' => 'inline',
    'group' => JS_LIBRARY,
    'weight' => -10.999999999,
  );
}

/**
 * @param string $cdn
 * @param array $javascript
 * @param string $path
 * @param string $min
 * * @param array $names
 */
function jquery_update_jqueryui_cdn($cdn, &$javascript, $path, $min, $names) {

  $jspath = $path . '/replace/ui/ui/' . ($min == '.min' ? 'minified/' : '');
  foreach ($names as $name => $file) {
    list($file_core, $file_updated) = is_array($file) ? $file : array($file, $file);
    $corefile = 'misc/ui/jquery.' . $file_core . '.min.js';
    unset($javascript[$name]['js'][$corefile]);
    $javascript[$name]['version'] = '1.10.2';
  }

  $javascript['ui']['js'][$cdn] = array(
    'data' => $cdn,
    'type' => 'external',
    'group' => JS_LIBRARY,
    'weight' => -11,
  );

  $javascript['effects']['dependencies'][] = array('system', 'ui');
}

/**
 * @param array $javascript
 * @param string $path
 * @param string $min
 * @param array $names
 */
function jquery_update_jqueryui_local(&$javascript, $path, $min, $names) {

  $jspath = $path . '/replace/ui/ui/' . ($min == '.min' ? 'minified/' : '');
  foreach ($names as $name => $file) {
    list($file_core, $file_updated) = is_array($file) ? $file : array($file, $file);
    $corefile = 'misc/ui/jquery.' . $file_core . '.min.js';
    $javascript[$name]['js'][$corefile]['data'] = $jspath . 'jquery.' . $file_updated . $min . '.js';
    $javascript[$name]['version'] = '1.10.2';
  }
}
